version: '3.6'

services:
  user-interface:
    build:
      context: services/ui
      dockerfile: Dockerfile-dev
    volumes:
      - './services/ui:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
    depends_on:
      - users-db
      - users

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-dev
    volumes:
      - './services/users:/usr/src/app'
    ports:
      - 5002:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@users-db:5432/users_dev
    depends_on:
      - users-db

  users-db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
    - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  teams:
    build:
      context: ./services/teams
      dockerfile: Dockerfile-dev
    volumes:
      - './services/teams:/usr/src/app'
    ports:
      - 5003:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@teams-db:5432/teams_dev
    depends_on:
      - teams-db

  teams-db:
    build:
      context: ./services/teams/project/db
      dockerfile: Dockerfile
    ports:
    - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  clubs:
    build:
      context: ./services/clubs
      dockerfile: Dockerfile-dev
    volumes:
      - './services/clubs:/usr/src/app'
    ports:
      - 5004:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@clubs-db:5432/clubs_dev
    depends_on:
      - clubs-db

  clubs-db:
    build:
      context: ./services/clubs/project/db
      dockerfile: Dockerfile
    ports:
    - 5437:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  referees:
    build:
      context: ./services/referees
      dockerfile: Dockerfile-dev
    volumes:
      - './services/referees:/usr/src/app'
    ports:
      - 5005:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@referees-db:5432/referees_dev
    depends_on:
      - referees-db

  referees-db:
    build:
      context: ./services/referees/project/db
      dockerfile: Dockerfile
    ports:
    - 5438:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres