version: '3.6'

services:
#  nginx:
#    container_name: nginx
#    build:
#      context: ./services/nginx
#      dockerfile: ./Dockerfile-dev
#    restart: always
#    ports:
#      - 80:80

  user-interface:
    container_name: ui
    build:
      context: services/ui
      dockerfile: Dockerfile-dev
    volumes:
      - './services/ui:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@users-db:5432/users_dev
    depends_on:
      - users-db

  users-db:
    container_name: users-db
    build:
      context: ./services/ui/project/db
      dockerfile: Dockerfile
    ports:
    - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  teams:
    container_name: teams
    build:
      context: ./services/teams
      dockerfile: Dockerfile-dev
    volumes:
      - './services/teams:/usr/src/app'
    ports:
      - 5003:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@teams-db:5432/teams_dev
    depends_on:
      - teams-db

  teams-db:
    container_name: teams-db
    build:
      context: ./services/teams/project/db
      dockerfile: Dockerfile
    ports:
    - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  leagues:
    container_name: leagues
    build:
      context: ./services/leagues
      dockerfile: Dockerfile-dev
    volumes:
      - './services/leagues:/usr/src/app'
    ports:
      - 5005:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@leagues-db:5432/leagues_dev
    depends_on:
      - leagues-db

  leagues-db:
    container_name: leagues-db
    build:
      context: ./services/leagues/project/db
      dockerfile: Dockerfile
    ports:
    - 5439:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  referees:
    container_name: referees
    build:
      context: ./services/referees
      dockerfile: Dockerfile-dev
    volumes:
      - './services/referees:/usr/src/app'
    ports:
      - 5006:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@referees-db:5432/referees_dev
    depends_on:
      - referees-db

  referees-db:
    container_name: referees-db
    build:
      context: ./services/referees/project/db
      dockerfile: Dockerfile
    ports:
    - 5438:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
